### ISSUE TITLE
Crashs since Xcode 14.3 compilation CIContext#render.

### ISSUE THREAD

**Issue by Goule** [shogo4405/HaishinKit.swift#1175]
### Describe the bug

Hello, 

Since I compiled my app with Xcode 14.3 I've noticed some crashes: 

<img width="1718" alt="Screenshot 2023-04-07 at 09 14 31" src="https://user-images.githubusercontent.com/21126201/230561934-e319ad0b-12ca-4eab-abf9-b976f63c3b29.png">

<img width="1146" alt="Screenshot 2023-04-07 at 09 21 45" src="https://user-images.githubusercontent.com/21126201/230562270-1955ea40-4727-4581-a3e7-197e470709e3.png">

It's hard to put code here since there are a lot of contexts with the app. But if someone has had the same issue since the Xcode 14.3 compilation maybe it can help.

### To Reproduce

1. It appear for some user when the stream start or randomly 
2. We have some simple video effect with images
3. We are pushing sample buffer from the camera 

### Expected behavior

No crash 

### Version

- HaishinKit 1.3.0 (we are not up to date so maybe it's fixed in the 1.4.5 ?)

### Smartphone info.

- iOS 16.4, 16.3 and 16.1
- Xcode 14.3

**Comment by shogo4405** [comment]
I have heard that Xcode 14.3 has bugs. Even if you update to 14.5, I think crashes will still occur.
Can I see “Données” tab? I want to know model names and free RAM size. By the way, are you using the patch for #986?

**Comment by Goule** [comment]
I've downgraded my Xcode version and all seems to be ok. It's probably a bug with Xcode 14.3...

Yes we are using the https://github.com/shogo4405/HaishinKit.swift/issues/986 patch ! 

Here are some data : 

<img width="798" alt="Screenshot 2023-04-08 at 10 40 11" src="https://user-images.githubusercontent.com/21126201/230712371-97c03fc1-5b0f-4168-aeff-2b780d6ee697.png">
<img width="837" alt="Screenshot 2023-04-08 at 10 40 14" src="https://user-images.githubusercontent.com/21126201/230712373-3f2ab413-5da0-4635-8ffa-69352240133e.png">
<img width="826" alt="Screenshot 2023-04-08 at 10 40 17" src="https://user-images.githubusercontent.com/21126201/230712374-89b29121-6a49-4100-a8cb-82d0ca84fe90.png">
<img width="846" alt="Screenshot 2023-04-08 at 10 40 20" src="https://user-images.githubusercontent.com/21126201/230712376-2e2823ed-42cf-44fb-917f-ac26ab368e04.png">
<img width="811" alt="Screenshot 2023-04-08 at 10 40 23" src="https://user-images.githubusercontent.com/21126201/230712379-68e00867-99d8-44db-8cc8-788b3fbe2c50.png">
<img width="789" alt="Screenshot 2023-04-08 at 10 40 26" src="https://user-images.githubusercontent.com/21126201/230712380-b13fc6f6-47f6-42ef-89d9-700401780f95.png">
<img width="825" alt="Screenshot 2023-04-08 at 10 40 29" src="https://user-images.githubusercontent.com/21126201/230712381-8e573c38-404d-46e4-9565-709e31908823.png">
<img width="814" alt="Screenshot 2023-04-08 at 10 40 36" src="https://user-images.githubusercontent.com/21126201/230712385-a94daaaa-8488-4de4-aab9-bcc9f5056c83.png">
<img width="972" alt="Screenshot 2023-04-08 at 10 40 41" src="https://user-images.githubusercontent.com/21126201/230712386-dc3cf15e-9971-4d87-a71b-ba51af21026f.png">

**Comment by shogo4405** [comment]
There may be a possibility that the detailed behavior of DispatchQueue has changed for situations with low memory capacity. Since all of them have low memory capacity, I'm concerned about the possibility of memory leaks occurring in Xcode 14.3.

I will investigate. thank you.

**Comment by Goule** [comment]
Thanks @shogo4405 !

**Comment by shogo4405** [comment]
I'm having difficulty reproducing the issue. I believe that the application crashes due to limited available memory, so I recommend that you limit memory usage on the application side to prevent this.
If it's a sample app, it uses around 110MB of memory. We haven't confirmed any memory leaks on the framework side.

Please let me know if there are other people who have the same issue.

**Comment by heestand-xyz** [comment]
I'm experiencing a similar issue. Crashes [here](https://github.com/shogo4405/HaishinKit.swift/blob/591e09092595c3905116390265da6acccf33bb71/Sources/Media/IORecorder.swift#L119) and [here](https://github.com/shogo4405/HaishinKit.swift/blob/591e09092595c3905116390265da6acccf33bb71/Sources/Net/NetStream.swift#L196).
The devices were low memory when the `EXC_BAD_ACCESS` happened.

**Comment by Goule** [comment]
Xcode 14.3.1 is out, hope it will fix it !

**Comment by Goule** [comment]
The issue still here with XCode 14.3.1 :(

**Comment by leo150** [comment]
Just a guess to figure out the source, maybe try to use no optimization for target's Build Settings - Swift Compiler - Optimization Level? And test it on small selection of user base.

**Comment by leo150** [comment]
Recalling a similar issue that happened on iOS 15 (?). There was a bug when user connects headphones, this would make the encoding to freeze for a few seconds, while `appendSampleBuffer` keeps executing until there's no memory. So the workaround was to wait until `videoIO` finishes encoding:

```
if self.limit.value > someNumber {
    return
}

self.limit.mutate { $0 += 1 }

mixer.videoIO.lockQueue.async {
    self.mixer.videoIO.encodeSampleBuffer(sampleBuffer)
    
    self.limit.mutate { $0 -= 1 }
}
```

**Comment by floriangbh** [comment]
Thanks @leo150 for the research lead, I'll try. I admit that I was waiting to see under Xcode 15 if this fixes anything..

**Comment by leo150** [comment]
Does anyone has luck with XCode 15? I can't compile with 14.2 anymore because of the recent [changes](https://github.com/shogo4405/HaishinKit.swift/blob/53689f0a44b4e10d8088c102d00b69ebb52c414a/Sources/Extension/AVAudioPCMBuffer%2BExtension.swift#L76).

**Comment by floriangbh** [comment]
Also waiting for feedbacks with Xcode 15 😅

**Comment by shogo4405** [comment]
Oops! The app being killed due to OOM (Out of Memory) when it exceeds device limits is an iOS specification. I believe it's up to the application to control memory usage and ensure it doesn't exceed the limits. Is everyone pausing xcode updates for now?

**Comment by floriangbh** [comment]
The weird things is that OOM appear since Xcode 14.3 compilation... 
I haven't tested yet with 15.0, maybe in november with progressive release...

**Comment by Goule** [comment]
Hello, 

I've just tested on XCode 15.0.1. 
Same issue with HaishinKit v1.6.1, always with low memory. 
Don't know how to investigate on it. @shogo4405 do you think it's leak on our side ? On on the library ? 

HaishinKit and Sonoma aren't compatible with XCode 14.2 so I can't use it to build :(

**Comment by floriangbh** [comment]
In my case the crash appear only in release mode, with `GCC_OPTIMIZATION_LEVEL = s` and `SWIFT_OPTIMIZATION_LEVEL = "-O"`, only when the available memory is low. 

I tried to figure out if there is a memory leak with the profiler, but all seem to be stable even in release mode. 

The crash appears here : 

<img width="647" alt="Screenshot 2023-10-27 at 12 57 07" src="https://github.com/shogo4405/HaishinKit.swift/assets/14054997/69219cd8-83ad-4a8f-8552-a4635e6688d7">


I'm also using `appendSampleBuffer` instead of camera attached.

**Comment by shogo4405** [comment]
@Goule  Goule  In that usage, if you follow the next steps, you can save memory usage and reduce the chances of crashing due to memory shortage:

**On the app side, set the following value:**
- Set the value to AVCaptureVideoDataOutput.alwaysDiscardsLateVideoFrames = true.

**For HaishinKit, you need to make the following adjustments:**
- Remove the section mixer.audioIO.lockQueue of mixer.videoIO.lockQueue in HaishinKit.
   - [Link](https://github.com/shogo4405/HaishinKit.swift/blob/release/1.6.x/Sources/Net/NetStream.swift#L253-L259)
   - When processing falls behind, data accumulates in these lockQueues, causing memory pressure.
- Perform stream.appendSampleBuffer on the same queue as set with AVCaptureVideoDataOutput.setSampleBufferDelegate.

**Comment by shogo4405** [comment]
@floriangbh Is "attachScreen" for iOS or macOS?

**Comment by Goule** [comment]
Thanks for your help @shogo4405 ! 

I will try with your recommendation. 

Before that I've tested with `rtmpStream.attachCamera`, and still have the same issue. So it's no coming from the extra code around the `appendSampleBuffer` I think...

<img width="1655" alt="Screenshot 2023-10-28 at 09 10 05" src="https://github.com/shogo4405/HaishinKit.swift/assets/21126201/ceb7816f-a8bf-49ef-86df-46fdd235692f">

I'll try to reproduce it with the sample project !

**Comment by shogo4405** [comment]
It is difficult to fix the issue of crashing due to memory capacity limits. I believe that what was previously undetectable as OOM can now be detected as crashes through Firebase. I think it's better to come up with solutions to avoid reaching memory limits rather than trying to fix it afterwards.

I'm adding code to the example that deliberately leads to memory shortage. It uses MemoryUsage.toEmpty() to use up memory without causing an OOM (Out of Memory) situation to that extent.
https://github.com/shogo4405/HaishinKit.swift/blob/main/Examples/iOS/MemoryUsage.swift#L15-L18

**Comment by Goule** [comment]
I'm not sure this is an OOM : 
- the application uses only 130/150Mb 
- an OOM is easily detectable with Xcode, after the application closes a message appears with "...has been killed by the operating system because it is using too much memory." 

It look more like a memory corruption with a bad access to unaloccated object or something else. 

I can reproduce it with Xcode an the memory when the app crash seem to be really ok, with 750MB free : 
<img width="544" alt="Screenshot 2023-10-28 at 17 41 05" src="https://github.com/shogo4405/HaishinKit.swift/assets/21126201/71f27aeb-21b4-4ecb-8922-104916f42148">

I will try to reduce the scope of my app with only simple screen to isolate the crash.

**Comment by shogo4405** [comment]
I can reproduce it.

## Prerequisites
- GCC_OPTIMIZATION_LEVEL = s
- WIFT_OPTIMIZATION_LEVEL = "-O"
- Prepare two MTHKViews. And stream.attachCamera, stream.attachAudio

## Reproduce
1. mthkView1.attachStream(stream)
2. mthkView1.attachStream(nil)
3. mthkView2.attachStream(stream)
    1. Crash CIContext#render method.

## How to fix it.
https://github.com/shogo4405/HaishinKit.swift/blob/main/Sources/Media/MTHKView.swift#L71
```swift
currentStream.mixer.videoIO.context = CIContext(mtlDevice: device!)
```
```swift
currentStream.mixer.videoIO.lockQueue.async {
  self.currentStream.mixer.videoIO.context = CIContext(mtlDevice: device!)
}
```
