### ISSUE TITLE
Audio not transmitting after disconnected from Bluetooth

### ISSUE THREAD

**Issue by vishakh-ncompass** [shogo4405/HaishinKit.swift#1322]
### Describe the bug

When simultaneously switching for streaming a video via mobile and bluetooth , after some time there is flickering/no audio at the receiver end.

### To Reproduce

1. Stream a video without bluetooth device/ AirPods . Check audio at receiver end you'll hear audio
2. Continue streaming with a bluetooth device. Again you can hear audio at the receiver end
3. Disconnect the bluetooth device. Still you can hear the audio at receiver end.
4. Now connect the bluetooth device. Now you'll notice a flickering audio / no audio at the receiver end

### Expected behavior

Even after multiple disconnect scenario of the bluetooth device the audio should be working fine.

### Version

5.0

### Smartphone info.

iOS 15+

**Comment by shogo4405** [comment]
1. What version is 5.0?
1. The possibility of the sampling rate changing midway might be the cause. However, it could also be due to compatibility issues with your media player, so I might not be able to address it from my side.

In the main branch, there is a feature to fix the sampling rate. Fixing it there might improve the situation.
