### ISSUE TITLE
ScreenCast

### ISSUE THREAD

**Issue by Amirhasanioox** [shogo4405/HaishinKit.swift#361]
how to add screen cast to another project ???

**Comment by shogo4405** [comment]
1. XCode menu -> [File] -> [New] -> [Target]
1. Choose "Broadcast Upload Extension"

You can add screencast templates :D

**Comment by gelb2** [comment]
Hi shogo4405. i would like to ask something about Screen Cast.

i'm trying to make screen cast work in my demo project. 
(Using Brocast Upload Extension. And App Group. Adding RTMP URL in func userDidFinishSetup() )
But When I Touch Start Broadcast Button at Control Center, Just One Alert Controller is Showed Up. "Live Broadcast to MyDemoApp has stopped due  to : (null)"

i think RTMP URL is Correct. because i already did Camera Broadcast With That URL. So i think i'm stucked at Coding Broadcast Upload Extension. i checked your Demo Project too, But i couldn't Understand Why My Demo App Doesn't work.

Could You Give Me More Hint About This Issue? Any Feedback Would be Appreciated

**Comment by shogo4405** [comment]
@gelb2 
Control Center will not call userDidFinishSetup().
You have to initial set up RPBroadcastSampleHandler#broadcastStarted.

**Comment by Amirhasanioox** [comment]
@shogo4405 I did what you said but the screen cast button in controll center did not appear there is just Recording button. 
Please help me!

**Comment by shogo4405** [comment]
I need more information on this.
Which part you don't understand?

**Comment by Amirhasanioox** [comment]
I add target and your codes and files into them but the button in control center does not appear can you say exactly what I need to add to target

**Comment by shogo4405** [comment]
Did you try this?

> 1. XCode menu -> [File] -> [New] -> [Target]
> 1. Choose "Broadcast Upload Extension"

After you can see "Your Project name" at Control Center.
First step is here.

**Comment by Amirhasanioox** [comment]
Yes, I did. 
but it does not appear on control center 😕

**Comment by shogo4405** [comment]
🤔 
I can. But you can't. I'm not sure. Please ask to Apple Developer Center.

**Comment by Amirhasanioox** [comment]
I try it in another empty project and it appear in control center but in another project that haishinkit or another files it doesn't appear

**Comment by Amirhasanioox** [comment]
Is there any code to disable or something else for ScreenCast ???

**Comment by Amirhasanioox** [comment]
I think it has problem with one file or code of haishinkit 🤔

**Comment by shogo4405** [comment]
Please consider to use Stackoverflow.
