### ISSUE TITLE
How to play rtmp at macOS

### ISSUE THREAD

**Issue by 29745560** [shogo4405/HaishinKit.swift#492]
I have an macOS project, and I want to play rtmp at audience living room, thank you very much!

**Comment by johnathan-terralogic** [comment]
Install VLC on mac, File -> Open Network -> paste RTMP link to URL field. That's it.

**Comment by Shoshin23** [comment]
But I'm unable to get this to work. So i downloaded the sample app and tried to open the rtmp://test:test@192.168.11.15/live on VLC and it didnt work. Also, I tried to append rtmp://test:test@192.168.11.15/live/live but this didn't either. 

Thanks!

**Comment by FD-** [comment]
I think the issue here stems from a misunderstanding: An RTMP server is needed in addition to the HaishinKit app. You then modify the server url and stream name in the app to point to that server, and also use it in VLC for playback. The default server address at 192.168.11.15 is just a placeholder that the developer of the library used.
At least that's how I understand it. I successfully played back the stream in VLC on macOS once I started my own RTMP server and configured HaishinKit and VLC accordingly.
